### ISSUE TITLE
completar lista de monitores

### ISSUE THREAD

**Issue by forero** [PythonBootcampUniandes/notas-de-clase#1]
ver el archivo [`monitores.md`](https://github.com/PythonBootcampUniandes/notas-de-clase/blob/master/monitores.md)

**Comment by mariacamilarg** [comment]
@forero me avisas si si crees que faltan mas para preguntarles!

**Comment by forero** [comment]
@mariacamilaremolinagutierrez si, necesitamos todos los que podamos.
